---

- name: Installing SysInternals Tools
  win_shell: ".\\install-sysinternals.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: sysinternals
  failed_when: "'Exception' in sysinternals.stdout"

- debug: msg="{{ sysinternals.stdout_lines }}"

- name: Installing AutorunsToWineventlog
  win_shell: ".\\install-autorunstowineventlog.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: autorunstowineventlog
  failed_when: "'Exception' in autorunstowineventlog.stdout"

- debug: msg="{{ autorunstowineventlog.stdout_lines }}"

- name: Installing Red Team Tooling
  win_shell: ".\\install-redteam.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: redteam
  failed_when: "'Exception' in redteam.stdout"

- debug: msg="{{ redteam.stdout_lines }}"

- name: Install Utilities
  win_shell: ".\\install-utilities.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: utilities
  failed_when: "'Exception' in utilities.stdout"
  ignore_errors: true